import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Database, ShieldCheck, Zap, ArrowRight, Layers, Lock, Cpu, Globe } from 'lucide-react';

export const BlockchainVisualizer: React.FC = () => {
    const [activeStep, setActiveStep] = useState(0);
    const [blocks, setBlocks] = useState<number[]>([]);
    
    useEffect(() => {
        const interval = setInterval(() => {
            setActiveStep((prev) => (prev + 1) % 5);
        }, 3000);

        const blockInterval = setInterval(() => {
            setBlocks(prev => [Math.floor(Date.now() / 12000), ...prev].slice(0, 5));
        }, 12000); // 12s block time (standard Ethereum/L2)

        return () => {
            clearInterval(interval);
            clearInterval(blockInterval);
        };
    }, []);

    const steps = [
        {
            title: "Agent Interaction",
            icon: <Cpu size={24} />,
            desc: "AI Agent performs a task (e.g. Inference). Telemetry is captured by the Xibalba SDK.",
            color: "var(--navy)"
        },
        {
            title: "Tri-Metric Ingestion",
            icon: <Zap size={24} />,
            desc: "Entropy, Grounding, and Sacrifice metrics are analyzed by the off-chain Scoring Engine.",
            color: "var(--gold)"
        },
        {
            title: "Xibalba Proof Generation",
            icon: <Lock size={24} />,
            desc: "A ZK-Reputation proof is generated by Xibalba's Secure Enclave to verify the score without exposing node data.",
            color: "var(--navy)"
        },
        {
            title: "Oracle Consensus",
            icon: <Globe size={24} />,
            desc: "Xibalba's Dual-Witness Oracle submits the verified state to the ReputationRegistry on Base L2.",
            color: "var(--gold)"
        },
        {
            title: "On-Chain AIS State",
            icon: <ShieldCheck size={24} />,
            desc: "The AIS state is updated globally. Smart contracts can now verify trust permissionlessly.",
            color: "var(--gold)"
        }
    ];

    return (
        <div className="enterprise-card" style={{ height: '100%', overflow: 'hidden' }}>

            <div className="card-header" style={{ borderBottom: '1px solid var(--border)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '12px', background: 'var(--navy-deep)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--gold)' }}>
                        <Layers size={20} />
                    </div>
                    <div>
                        <h2 style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--navy)', textTransform: 'uppercase', letterSpacing: '0.25em', margin: 0 }}>Protocol Workflow</h2>
                        <span style={{ fontSize: '0.6rem', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.15em' }}>Real-Time State Propagation</span>
                    </div>
                </div>
                <div className="badge badge-slate" style={{ fontSize: '0.55rem', letterSpacing: '0.1em' }}>
                    LAST BLOCK: #{blocks[0] || '...'}
                </div>
            </div>
            <div style={{ padding: '16px 32px', background: 'var(--background)', fontSize: '0.65rem', color: 'var(--text-secondary)', lineHeight: 1.5, borderBottom: '1px solid var(--border)', textAlign: 'justify' }}>
                The cryptographic pipeline of the Integrity Protocol. From raw agent telemetry ingestion to ZK-Reputation proof generation and final settlement on the Base L2 smart contracts. This visualizer traces the lifecycle of a single reputation update, demonstrating how off-chain telemetry is securely aggregated, cryptographically proven via zero-knowledge circuits, and ultimately anchored to a permissionless blockchain for immutable, public verification.
            </div>

            <div className="card-body" style={{ display: 'flex', flexDirection: 'column' as const, padding: '40px' }}>
                {/* Visual Pipeline */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'relative', marginBottom: '60px' }}>
                    {/* Connecting Line Background */}
                    <div style={{ position: 'absolute', top: '50%', left: '0', right: '0', height: '2px', background: 'var(--border)', zIndex: 1, transform: 'translateY(-50%)' }}></div>
                    
                    {/* Active Line Progress */}
                    <motion.div 
                        animate={{ width: `${(activeStep / (steps.length - 1)) * 100}%` }}
                        style={{ position: 'absolute', top: '50%', left: '0', height: '2px', background: 'var(--gold)', zIndex: 2, transform: 'translateY(-50%)' }}
                    />

                    {steps.map((step, i) => (
                        <div key={i} style={{ position: 'relative', zIndex: 3, display: 'flex', flexDirection: 'column' as const, alignItems: 'center' }}>
                            <motion.div
                                animate={{ 
                                    scale: activeStep === i ? 1.2 : 1,
                                    backgroundColor: activeStep === i ? 'var(--background)' : 'var(--off-white)',
                                    borderColor: activeStep === i ? 'var(--gold)' : 'var(--border)',
                                    boxShadow: activeStep === i ? 'var(--shadow-gold)' : 'none'
                                }}
                                style={{ 
                                    width: '56px', 
                                    height: '56px', 
                                    borderRadius: '50%', 
                                    border: '2px solid', 
                                    display: 'flex', 
                                    alignItems: 'center', 
                                    justifyContent: 'center',
                                    color: activeStep === i ? 'var(--gold)' : 'var(--slate)',
                                    background: 'var(--background)',
                                    transition: 'all 0.3s'
                                }}
                            >
                                {step.icon}
                            </motion.div>
                            <span style={{ 
                                position: 'absolute', 
                                top: '65px', 
                                whiteSpace: 'nowrap', 
                                fontSize: '0.55rem', 
                                fontWeight: 800, 
                                textTransform: 'uppercase', 
                                letterSpacing: '0.1em',
                                color: activeStep === i ? 'var(--navy)' : 'var(--text-muted)'
                            }}>
                                {step.title.split(' ')[0]}
                            </span>
                        </div>
                    ))}
                </div>

                {/* Step Detail Card */}
                <AnimatePresence mode="wait">
                    <motion.div
                        key={activeStep}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -20 }}
                        style={{ 
                            backgroundColor: 'var(--off-white)', 
                            border: '1px solid var(--border)', 
                            padding: '32px', 
                            borderRadius: 'var(--r-md)',
                            display: 'flex',
                            gap: '24px',
                            alignItems: 'center'
                        }}
                    >
                        <div style={{ 
                            width: '64px', 
                            height: '64px', 
                            borderRadius: '16px', 
                            background: 'white', 
                            border: '1px solid var(--border)', 
                            display: 'flex', 
                            alignItems: 'center', 
                            justifyContent: 'center', 
                            color: steps[activeStep].color,
                            boxShadow: 'var(--shadow-sm)'
                        }}>
                            {steps[activeStep].icon}
                        </div>
                        <div style={{ flex: 1 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                                <span style={{ fontSize: '0.6rem', fontWeight: 900, color: 'var(--gold)', textTransform: 'uppercase', letterSpacing: '0.2em' }}>XIBALBA AUTHENTICATION</span>
                                <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--navy)', margin: 0, fontFamily: 'Playfair Display, serif' }}>{steps[activeStep].title}</h3>
                            </div>
                            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>
                                {steps[activeStep].desc}
                            </p>
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column' as const, alignItems: 'center', opacity: activeStep >= 2 ? 1 : 0.2, transition: 'opacity 0.5s' }}>
                             <ShieldCheck size={32} style={{ color: 'var(--gold)' }} />
                             <span style={{ fontSize: '0.5rem', fontWeight: 900, marginTop: '8px', color: 'var(--navy)' }}>AUDITED</span>
                        </div>
                        <ArrowRight size={24} style={{ color: 'var(--border)' }} />
                    </motion.div>
                </AnimatePresence>

                {/* Smart Contract Interaction Simulator */}
                <div style={{ marginTop: '40px', paddingTop: '32px', borderTop: '1px solid var(--border)' }}>
                    <div className="flex-between mb-4">
                        <h4 style={{ fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.25em', margin: 0, display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Database size={14} /> Smart Contract State: `ReputationRegistry.sol`
                        </h4>
                        <span className="mono" style={{ fontSize: '0.55rem', color: 'var(--gold)' }}>// BASE_L2_CONNECTED</span>
                    </div>
                    
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: '20px' }}>
                        <div style={{ padding: '20px', background: 'var(--navy-deep)', borderRadius: '12px', color: 'white', fontSize: '0.75rem' }}>
                            <p className="mono" style={{ color: 'var(--gold)', marginBottom: '12px' }}>contract ReputationRegistry {"{"}</p>
                            <p className="mono" style={{ paddingLeft: '16px', opacity: 0.8 }}>struct AgentProfile {"{"}</p>
                            <p className="mono" style={{ paddingLeft: '32px' }}>uint256 <span style={{ color: 'var(--gold)' }}>ais</span>: <motion.span animate={{ opacity: [1, 0.4, 1] }} transition={{ repeat: Infinity, duration: 2 }}>840</motion.span></p>
                            <p className="mono" style={{ paddingLeft: '32px' }}>uint256 <span style={{ color: 'var(--gold)' }}>jobCount</span>: 1422</p>
                            <p className="mono" style={{ paddingLeft: '32px' }}>bool <span style={{ color: 'var(--gold)' }}>isVerified</span>: true</p>
                            <p className="mono" style={{ paddingLeft: '16px', opacity: 0.8 }}>{"}"}</p>
                            <p className="mono" style={{ color: 'var(--gold)' }}>{"}"}</p>
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column' as const, gap: '12px' }}>
                            <div style={{ padding: '16px', background: 'var(--off-white)', borderRadius: '12px', border: '1px solid var(--border)' }}>
                                <div className="flex-between mb-2">
                                    <span style={{ fontSize: '0.6rem', fontWeight: 800, color: 'var(--text-muted)' }}>NETWORK GAS (L2)</span>
                                    <span className="mono" style={{ fontSize: '0.65rem', fontWeight: 700 }}>0.00012 ETH</span>
                                </div>
                                <div style={{ height: '4px', background: 'var(--border)', borderRadius: '2px', overflow: 'hidden' }}>
                                    <motion.div animate={{ width: ['20%', '80%', '40%'] }} transition={{ repeat: Infinity, duration: 5 }} style={{ height: '100%', background: 'var(--gold)' }} />
                                </div>
                            </div>
                            <div style={{ padding: '16px', background: 'var(--off-white)', borderRadius: '12px', border: '1px solid var(--border)' }}>
                                <div className="flex-between mb-2">
                                    <span style={{ fontSize: '0.6rem', fontWeight: 800, color: 'var(--text-muted)' }}>ZK-REPUTATION VERIFICATION</span>
                                    <span className="mono" style={{ fontSize: '0.65rem', fontWeight: 700, color: 'var(--gold)' }}>VALID</span>
                                </div>
                                <div className="flex gap-1">
                                    {[1,2,3,4,5,6,7,8,9,10].map(i => (
                                        <motion.div key={i} animate={{ opacity: [0.2, 1, 0.2] }} transition={{ delay: i * 0.1, repeat: Infinity, duration: 1.5 }} style={{ flex: 1, height: '4px', background: 'var(--gold)', borderRadius: '2px' }} />
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
